### ISSUE TITLE
Give user feedback if user clicks save drawing and no drawing is present 

### ISSUE THREAD

**Issue by cdrake** [niivue/niivue-desktop#4]

**Comment by hanayik** [comment]
@cdrake , were you thinking of a message dialog or something for this?

**Comment by cdrake** [comment]
Yes

**Comment by hanayik** [comment]
Cool. Sounds good!

From: Christopher Drake ***@***.***>
Date: Monday, 13 February 2023 at 4:41 pm
To: niivue/niivue-desktop ***@***.***>
Cc: Taylor Hanayik ***@***.***>, Comment ***@***.***>
Subject: Re: [niivue/niivue-desktop] Give user feedback if user clicks save drawing and no drawing is present (Issue #4)

Yes
